source "http://rubygems.org"
gem "sinatra", :git => "git://github.com/sinatra/sinatra.git", :require => "sinatra/base"
gem "thin"
gem "rack-flash"
gem "rack-rewrite", :require => "rack/rewrite"
gem "haml"
gem "compass", "~>0.10"
gem "i18n"
gem "json"
gem "sequel"
gem "sqlite3"
gem "serialport"
gem "rdiscount"
gem "pony"
gem "wirble", :group => :development
